# Generated by Django 2.2 on 2020-04-24 15:43

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=256)),
                ('ip', models.GenericIPAddressField(blank=True, default='', null=True, verbose_name='آی\u200cپی')),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'دانلود',
                'verbose_name_plural': 'دانلودها',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('access_token', models.CharField(max_length=60, unique=True)),
                ('refresh_token', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('access_token_created_at', models.DateTimeField(auto_now=True)),
                ('refresh_token_created_at', models.DateTimeField(auto_now_add=True)),
                ('access_token_lifetime', models.IntegerField(default=10)),
                ('refresh_token_lifetime', models.IntegerField(default=120)),
                ('access_ip', models.GenericIPAddressField(verbose_name='آی\u200cپی')),
                ('agent', models.CharField(default=None, max_length=80)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'توکن',
                'verbose_name_plural': 'توکن\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, default='', editable=False, null=True, verbose_name='آی\u200cپی سازنده')),
                ('updated_ip', models.GenericIPAddressField(blank=True, default='', editable=False, null=True, verbose_name='آی\u200cپی ادیتور')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_preferences_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_preferences_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تنظیم',
                'verbose_name_plural': 'تنظیمات',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MobileTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, default='', editable=False, null=True, verbose_name='آی\u200cپی سازنده')),
                ('updated_ip', models.GenericIPAddressField(blank=True, default='', editable=False, null=True, verbose_name='آی\u200cپی ادیتور')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='شماره')),
                ('ip', models.GenericIPAddressField(verbose_name='آی\u200cپی')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_mobiletemp_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_mobiletemp_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'شماره بالقوه',
                'verbose_name_plural': 'شماره\u200cهای بالقوه',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'roles')},
            },
        ),
        migrations.CreateModel(
            name='Confirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, default='', editable=False, null=True, verbose_name='آی\u200cپی سازنده')),
                ('updated_ip', models.GenericIPAddressField(blank=True, default='', editable=False, null=True, verbose_name='آی\u200cپی ادیتور')),
                ('which', models.IntegerField(choices=[(1, 'Email'), (2, 'Mobile'), (10, 'Reset Password')], default=2)),
                ('code', models.CharField(max_length=36)),
                ('count', models.IntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_confirm_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_confirm_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تأیید',
                'verbose_name_plural': 'تأییدات',
                'abstract': False,
                'unique_together': {('user', 'which')},
            },
        ),
    ]
