# Generated by Django 2.2 on 2020-04-15 14:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='roles',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='roles',
            unique_together={('user', 'roles')},
        ),
    ]
