# Generated by Django 2.2 on 2020-05-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeta',
            name='postal_code',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
