# Generated by Django 2.2 on 2020-05-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usermeta_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermeta',
            name='birth_place',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='postal_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='work_address',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
    ]
