# Generated by Django 2.2 on 2020-04-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usermeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='access_token',
            field=models.CharField(db_index=True, max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='mobile',
            field=models.CharField(default='', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='national_id',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
