# Generated by Django 2.2 on 2020-05-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200508_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='access_token_lifetime',
            field=models.IntegerField(default=120),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='fathers_name',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='home_address',
            field=models.TextField(blank=True, default=None, max_length=120),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='identity_card_number',
            field=models.CharField(blank=True, default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='national_id',
            field=models.CharField(blank=True, default=None, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='tel',
            field=models.CharField(blank=True, default=None, max_length=15),
        ),
    ]
