# Generated by Django 2.2 on 2020-05-01 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_verificationsms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermeta',
            old_name='veriffication_type',
            new_name='verification_type',
        ),
    ]
