# Generated by Django 2.2 on 2020-05-03 21:08

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_auto_20200501_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('body', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('ctype', models.IntegerField(choices=[(1, 'SMS'), (2, 'Email')], default=1)),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Inprogress'), (2, 'Retry'), (9, 'Failed'), (10, 'Done')], default=0)),
                ('target', models.CharField(max_length=50)),
                ('target_group', models.IntegerField(blank=True, null=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('stop_at', models.DateTimeField(blank=True, null=True)),
                ('index', models.CharField(default='', max_length=20)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('gtw', models.IntegerField(choices=[(0, 'unknown gateway'), (1, 'django send mail'), (11, 'parsa sms'), (12, 'parsa template sms')], default=0)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
