# Generated by Django 2.1.5 on 2019-02-01 19:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sandogh.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, default='', editable=False, null=True, verbose_name='آی\u200cپی سازنده')),
                ('updated_ip', models.GenericIPAddressField(blank=True, default='', editable=False, null=True, verbose_name='آی\u200cپی ادیتور')),
                ('body', models.TextField(default='')),
                ('type', models.IntegerField(choices=[(1, 'اطلاعیه'), (2, 'مقررات')], default=1)),
                ('publish_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sandogh_announcement_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلانات',
            },
        ),
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, default='', editable=False, null=True, verbose_name='آی\u200cپی سازنده')),
                ('updated_ip', models.GenericIPAddressField(blank=True, default='', editable=False, null=True, verbose_name='آی\u200cپی ادیتور')),
                ('mobile', models.CharField(blank=True, db_index=True, default='', max_length=100, null=True, verbose_name='Mobile')),
                ('tel', models.CharField(blank=True, db_index=True, default='', max_length=30, verbose_name='Telephone 1')),
                ('tel2', models.CharField(blank=True, db_index=True, default='', max_length=30, verbose_name='Telephone 2')),
                ('fax', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Fax')),
                ('desc', models.CharField(blank=True, default='', max_length=1024, verbose_name='Description')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('birthday', models.CharField(blank=True, default='0000', editable=False, max_length=4, verbose_name='Birth Day')),
                ('sex', models.SmallIntegerField(blank=True, choices=[(-1, 'Unknown'), (1, 'Male'), (0, 'Female')], default=-1, null=True, verbose_name='Gender')),
                ('membership', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Membership')),
                ('notification', models.CharField(blank=True, default='', max_length=1024, verbose_name='Notification')),
                ('mobile_confirm', models.BooleanField(choices=[(False, 'Not confirmed'), (True, 'Confirmed')], default=False, verbose_name='Mobile Confirm')),
                ('email_confirm', models.BooleanField(choices=[(False, 'Not confirmed'), (True, 'Confirmed')], default=False, verbose_name='Email Confirm')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sandogh_borrower_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sandogh_borrower_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Identification')),
            ],
            options={
                'verbose_name': 'وام گيرنده',
                'verbose_name_plural': 'وام گیرندگان',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, default='', editable=False, null=True, verbose_name='آی\u200cپی سازنده')),
                ('updated_ip', models.GenericIPAddressField(blank=True, default='', editable=False, null=True, verbose_name='آی\u200cپی ادیتور')),
                ('image', models.ImageField(upload_to=sandogh.models.upload_to_documents)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sandogh_document_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مدرک',
                'verbose_name_plural': 'مدارک',
            },
        ),
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, default='', editable=False, null=True, verbose_name='آی\u200cپی سازنده')),
                ('updated_ip', models.GenericIPAddressField(blank=True, default='', editable=False, null=True, verbose_name='آی\u200cپی ادیتور')),
                ('name', models.CharField(max_length=100)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='admin username')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sandogh_lender_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sandogh_lender_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'صندوق',
                'verbose_name_plural': 'صندوق\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, default='', editable=False, null=True, verbose_name='آی\u200cپی سازنده')),
                ('updated_ip', models.GenericIPAddressField(blank=True, default='', editable=False, null=True, verbose_name='آی\u200cپی ادیتور')),
                ('debt', models.BigIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sandogh_member_created_by', to=settings.AUTH_USER_MODEL)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sandogh.Lender')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sandogh_member_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'عضو',
                'verbose_name_plural': 'اعضا',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, default='', editable=False, null=True, verbose_name='آی\u200cپی سازنده')),
                ('updated_ip', models.GenericIPAddressField(blank=True, default='', editable=False, null=True, verbose_name='آی\u200cپی ادیتور')),
                ('amount', models.BigIntegerField()),
                ('date', models.DateField()),
                ('type', models.IntegerField(choices=[(0, 'قسط'), (1, 'پس انداز')])),
                ('gateway', models.IntegerField()),
                ('desc', models.CharField(blank=True, default='', max_length=512)),
                ('serial', models.CharField(blank=True, default='', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sandogh_payment_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sandogh_payment_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, default='', editable=False, null=True, verbose_name='آی\u200cپی سازنده')),
                ('updated_ip', models.GenericIPAddressField(blank=True, default='', editable=False, null=True, verbose_name='آی\u200cپی ادیتور')),
                ('type', models.IntegerField(choices=[(1, 'TYPE1'), (2, 'TYPE2')], default=1)),
                ('body', models.CharField(default='', max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('staff_review_body', models.CharField(default='', max_length=300)),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'Confirmed'), (10, 'Rejected')], default=1)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sandogh_request_created_by', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sandogh.Member')),
                ('staff_reviewer', models.ForeignKey(default='', max_length=300, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sandogh_request_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'درخواست',
                'verbose_name_plural': 'درخواست\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, default='', editable=False, null=True, verbose_name='آی\u200cپی سازنده')),
                ('updated_ip', models.GenericIPAddressField(blank=True, default='', editable=False, null=True, verbose_name='آی\u200cپی ادیتور')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sandogh_staff_created_by', to=settings.AUTH_USER_MODEL)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sandogh.Lender')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sandogh_staff_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'کارمند',
                'verbose_name_plural': 'کارمندها',
            },
        ),
        migrations.CreateModel(
            name='StaffReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, default='', editable=False, null=True, verbose_name='آی\u200cپی سازنده')),
                ('updated_ip', models.GenericIPAddressField(blank=True, default='', editable=False, null=True, verbose_name='آی\u200cپی ادیتور')),
                ('enter_at', models.DateTimeField()),
                ('exit_at', models.DateTimeField()),
                ('desc', models.CharField(blank=True, default='', max_length=512)),
                ('performance', models.IntegerField(blank=True, default=0)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sandogh_staffreport_created_by', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sandogh.Staff')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sandogh_staffreport_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, default='', editable=False, null=True, verbose_name='آی\u200cپی سازنده')),
                ('updated_ip', models.GenericIPAddressField(blank=True, default='', editable=False, null=True, verbose_name='آی\u200cپی ادیتور')),
                ('number', models.IntegerField(default=0)),
                ('due_date', models.DateField()),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sandogh_turn_created_by', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sandogh.Request')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sandogh_turn_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نوبت',
                'verbose_name_plural': 'نوبت\u200cها',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sandogh.Member'),
        ),
        migrations.AddField(
            model_name='document',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sandogh_document_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='lender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sandogh.Lender'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sandogh_announcement_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
