# Generated by Django 2.1.5 on 2019-02-02 17:50

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sandogh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, default='', editable=False, null=True, verbose_name='آی\u200cپی سازنده')),
                ('updated_ip', models.GenericIPAddressField(blank=True, default='', editable=False, null=True, verbose_name='آی\u200cپی ادیتور')),
                ('name', models.CharField(max_length=100)),
                ('code', models.IntegerField(blank=True, choices=[(1, 'آینده'), (2, 'اقتصاد نوین'), (3, 'ایران زمین'), (4, 'انصار'), (5, 'پست بانک'), (6, 'پاسارگاد'), (7, 'پارسیان'), (8, 'تجارت'), (9, 'توسعه صادرات'), (10, 'توسعه تعاون'), (11, 'حکمت'), (12, 'خاورمیانه'), (13, 'دی'), (14, 'رفاه'), (15, 'سامان'), (16, 'سرمایه'), (17, 'سینا'), (18, 'سپه'), (19, 'شهر'), (20, 'قرض الحسنه رسالت'), (21, 'قرض الحسنه مهر'), (22, 'قوامین'), (23, 'کشاورزی'), (24, 'کارآفرین'), (25, 'صنعت و معدن'), (26, 'صادرات'), (27, 'گردشگری'), (28, 'ملت'), (29, 'مسکن'), (30, 'ملی')], null=True)),
                ('merchant_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sandogh_bank_created_by', to=settings.AUTH_USER_MODEL)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sandogh.Lender')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sandogh_bank_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'بانک',
                'verbose_name_plural': 'بانک\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, default='', editable=False, null=True, verbose_name='آی\u200cپی سازنده')),
                ('updated_ip', models.GenericIPAddressField(blank=True, default='', editable=False, null=True, verbose_name='آی\u200cپی ادیتور')),
                ('type_id', models.IntegerField(choices=[(1, 'POS'), (2, 'IPG'), (8, 'COUNTER')])),
                ('desc', models.CharField(blank=True, default='', max_length=100)),
                ('terminal_id', models.CharField(blank=True, default='', max_length=100)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict, editable=False)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sandogh.Bank')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sandogh_terminal_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sandogh_terminal_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ترمینال',
                'verbose_name_plural': 'ترمینال\u200cها',
            },
        ),
        migrations.RemoveField(
            model_name='payment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='gateway',
        ),
        migrations.AddField(
            model_name='payment',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='terminal',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='sandogh.Terminal'),
            preserve_default=False,
        ),
    ]
