# Generated by Django 2.2 on 2020-05-08 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sandogh', '0002_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, 'new'), (1, 'waiting for verify'), (2, 'rejected'), (3, 'verified')], default=0)),
                ('lender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sandogh.Lender')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'درخواست عضویت',
                'verbose_name_plural': 'درخواست\u200cهای عضویت',
            },
        ),
    ]
