# Generated by Django 2.2 on 2020-04-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandogh', '0002_auto_20190202_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='lender',
            name='domain',
            field=models.CharField(default='', max_length=60),
        ),
    ]
